---
title: "Group 02 CA pollution burden"
author: "Kort Alexander and Chelsie McWhorter"
date: "11/14/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(janitor)
library(here)
```

###Part A. Partner 1 | Data input

```{r}
ces <- read_csv(here("data", "ces3demographics.csv")) %>% 
  clean_names()
```

###Part B. Partner 2 | Initial graph creation. 

```{r}
ces_graph <- ggplot(data = ces, aes(x = white_percent, y = ces_3_0_score)) +
  geom_hex() +
  scale_fill_gradient(low = "plum3", high = "darkorchid4") +
  theme_minimal() +
  labs(x = "% white population", y = "CES 3.0 score")
ces_graph
```

Overall, the trend of these data show that the areas that have lower percentages of white occupants also have a lower CES 3.0 score, which means they have lower pollution burdens than non-whites. 

Citation: Eng, Tiffany. (January 2017). *CalEnviroScreen 3.0* [Infographic]. https://caleja.org/wp-content/uploads/2015/09/CES3.0-5.pdf